export const DEFAULT_CONFIG_TOML = [
  '[meeting]',
  'end_keywords = ["end", "done", "終了"]',
  'allowed_event_types = ["note", "decision", "task", "parking"]',
  '',
  '[paths]',
  'base_dir = ".mtg"',
  'session_file = "session.json"',
  'event_dir = "events"',
  'exec_file = "exec.jsonl"',
  'doc_file = "docs/knowledge/decisions.md"',
  'issue_file = "docs/issues/tasks.md"',
  'minutes_dir = "docs/minutes"',
  '',
  '[retrieval]',
  'top_entries = 8',
  'top_inner_entries = 8',
  'preview_lines = 40',
  'max_content_chars = 30000',
  'max_sources = 5',
  'excluded_dirs = [".git", ".mtg"]',
  'excluded_extensions = [".png", ".jpg", ".jpeg", ".gif", ".pdf", ".pyc"]',
  'fallback_files = ["README.md", "orgai/main.ts"]',
  '',
].join('\n');
